### ISSUE TITLE
not working on Alienware 17 R3

### ISSUE THREAD

**Issue by anees042** [bchretien/AlienFxLite#10]
the program only displays the following and exit ;

Device found: 187c:0528

**Comment by jakeday** [comment]
This is fixed with my [pull request](https://github.com/bchretien/AlienFxLite/pull/11)

**Comment by bchretien** [comment]
@anees042 can you confirm that the PR from @jakeday solved your issue (merged to master)?

**Comment by anees042** [comment]
yeah, it's working.. sorry for late reply..

thanks a lot guys..
