### ISSUE TITLE
Pre-compiled Version

### ISSUE THREAD

**Issue by thobianchi** [bchretien/AlienFxLite#12]
It's possible to upload a precompiled version? I don't want to compile it myself.

**Comment by bchretien** [comment]
Thanks for the suggestion, but I have no plan to provide a precompiled version.

**Comment by Victor-Villacis** [comment]
Awesome build and thanks for taking the time to do this. I have a question. What goes in the place of 
"YOUR_INSTALL_PREFIX" here?`$ cmake .. -DCMAKE_INSTALL_PREFIX="YOUR_INSTALL_PREFIX"`

**Comment by impsdc** [comment]
Yes i do not understand how Cmake works even with the documentation. Can you please provide the exact syntax
