### ISSUE TITLE
Error on M17x R4

### ISSUE THREAD

**Issue by Robfz** [bchretien/AlienFxLite#2]
Hi, I am trying to use the program on a M17x R4. I am getting the following error:

```
" The application was unable to communicate with the alienfx device. The device is not present, or the application lacks sufficient rights to access the device."
```

According to the console output, the device is found: 

```
Device found: 187c:0520
```

Also,  this is the output of 'sudo lsusb | grep -i alien':

```
$ sudo lsusb | grep -i alien
Bus 003 Device 003: ID 187c:0520 Alienware Corporation 
```

Thanks.

**Comment by bchretien** [comment]
Does your user have the proper USB rights, or did you run the program with `sudo`?

**Comment by Robfz** [comment]
Ran the program with sudo.

**Comment by bchretien** [comment]
Ok my bad, I had a controller for the M17x R3 locally, but it was not pushed and has not been tested yet. Apparently the M17x R4 has the same id (`0x0520`), so it should work with it. Feel free to test with the latest commit, and report any issue.

**Comment by Robfz** [comment]
It is working! Will report any issue. Thanks.

**Comment by bchretien** [comment]
Ok, I'm closing this issue. Feel free to reopen it for any related problem.
