### ISSUE TITLE
Cmake compiling issues

### ISSUE THREAD

**Issue by davebattles** [bchretien/AlienFxLite#3]
http://pastebin.com/raw/TuiF9Fgb

Cmake failed both manually and on AUR. 

Using Openjdk 8 and cmake 3.5.1-1

-- Could NOT find JNI (missing:  JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Java (missing: Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE
  Java_JAVADOC_EXECUTABLE Development) (found version "1.8.0.77")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindJava.cmake:244 (find_package_handle_standard_args)
  CMakeLists.txt:64 (FIND_PACKAGE)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JAVA_INCLUDE_PATH (ADVANCED)
   used as include directory in directory /tmp/yaourt-tmp-vox/aur-alienfx-lite/src/AlienFxLite-1.0
   used as include directory in directory /tmp/yaourt-tmp-vox/aur-alienfx-lite/src/AlienFxLite-1.0
   used as include directory in directory /tmp/yaourt-tmp-vox/aur-alienfx-lite/src/AlienFxLite-1.0
JAVA_INCLUDE_PATH2 (ADVANCED)
   used as include directory in directory /tmp/yaourt-tmp-vox/aur-alienfx-lite/src/AlienFxLite-1.0
   used as include directory in directory /tmp/yaourt-tmp-vox/aur-alienfx-lite/src/AlienFxLite-1.0
   used as include directory in directory /tmp/yaourt-tmp-vox/aur-alienfx-lite/src/AlienFxLite-1.0

-- Configuring incomplete, errors occurred!
See also "/tmp/yaourt-tmp-vox/aur-alienfx-lite/src/AlienFxLite-1.0/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in prepare().
    Aborting...
==> ERROR: Makepkg was unable to build alienfx-lite.
==> Restart building alienfx-lite ? [y/N]
==> -------------------------------------
==>

**Comment by bchretien** [comment]
Do you have the `jdk8-openjdk` package installed? `Java_JAVAC_EXECUTABLE` and `Java_JAVAH_EXECUTABLE` are provided by `java-environment-common`, a dependency of `jdk8-openjdk`, but CMake does not seem to be finding then.

**Comment by davebattles** [comment]
Ok wow, I had jre8-openjdk and not jdk8-openjdk. That was completely my fault. I'm still not sure what the difference between the two is, but thank you for your help. It compiled flawlessly.

**Comment by bchretien** [comment]
Ok, nice! I will add `java-environment-common` as a dependency to the AUR package.
