### ISSUE TITLE
libAlien64.so : no such file or directory

### ISSUE THREAD

**Issue by dipack95** [bchretien/AlienFxLite#4]
Hi, after downloading the PKGBUILD from [AUR](https://aur.archlinux.org/packages/alienfx-lite/), when I run `makepkg -sri`, after reaching the build step, wherein it runs the `make` command  in the `build/` directory, it fails, citing this error:

`[ 60%] Built target AlienFX
[ 60%] Built target Images_to_jar
/home/dipack/aur-packages/alienfx-lite/src/AlienFxLite-1.1/build/lib/libAlien64.so : no such file or directory
make[2]: *** [CMakeFiles/Lib_to_jar.dir/build.make:61: Lib_to_jar] Error 1
make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/Lib_to_jar.dir/all] Error 2
make: *** [Makefile:128: all] Error 2`

Could you help me out with this?

**Comment by bchretien** [comment]
I think I found the issue, you can try with the latest commit. I'll update the PKGBUILD if you confirm that this solves the problem for you.

**Comment by Soulsuke** [comment]
Just had the same issue with the AUR package, but the latest git commit (7b5e30f8c0c4476fa6f6b6f216f7c466bb11737d) fixed it for me!

Really appreciate your work ^^

**Comment by bchretien** [comment]
Thanks for the feedback, AUR package updated ;)
