### ISSUE TITLE
just got an older Alienware product: M18xR1 and i cant get this working

### ISSUE THREAD

**Issue by chuquel** [bchretien/AlienFxLite#9]
btw you guys are awesome for building this!!!

many thanks in advance

Chuck K.

[ 20%] Building Java objects for AlienFX.jar
src/java/uk/co/progger/alienFXLite/alienfx/AlienFXProfiles.java:18: type javax.swing.ComboBoxModel does not take parameters
public class AlienFXProfiles  implements ComboBoxModel<AlienFXProfile> {
                                                      ^
src/java/uk/co/progger/alienFXLite/gui/ProfileSelectionPanel.java:31: type javax.swing.JComboBox does not take parameters
	private JComboBox<AlienFXProfile> chooseProfileBox;
	                 ^
src/java/uk/co/progger/alienFXLite/alienfx/AlienFXProfiles.java:101: method does not override or implement a method from a supertype
	@Override
	^
src/java/uk/co/progger/alienFXLite/alienfx/AlienFXProfiles.java:108: method does not override or implement a method from a supertype
	@Override
	^
src/java/uk/co/progger/alienFXLite/alienfx/AlienFXProfiles.java:116: method does not override or implement a method from a supertype
	@Override
	^
src/java/uk/co/progger/alienFXLite/alienfx/AlienFXProfiles.java:121: method does not override or implement a method from a supertype
	@Override
	^
src/java/uk/co/progger/alienFXLite/alienfx/AlienFXProfiles.java:128: method does not override or implement a method from a supertype
	@Override
	^
src/java/uk/co/progger/alienFXLite/alienfx/AlienFXProfiles.java:133: method does not override or implement a method from a supertype
	@Override
	^
src/java/uk/co/progger/alienFXLite/gui/ProfileSelectionPanel.java:47: type javax.swing.JComboBox does not take parameters
		chooseProfileBox = new JComboBox<AlienFXProfile>(profiles);
		                                ^
9 errors
CMakeFiles/AlienFX.dir/build.make:116: recipe for target 'CMakeFiles/AlienFX.dir/java_compiled_AlienFX' failed
make[2]: *** [CMakeFiles/AlienFX.dir/java_compiled_AlienFX] Error 1
CMakeFiles/Makefile2:212: recipe for target 'CMakeFiles/AlienFX.dir/all' failed
make[1]: *** [CMakeFiles/AlienFX.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bchretien** [comment]
Which Java JDK are you using? This was tested with Java 7 and 8, but I've got the feeling you're using Java 6.

**Comment by chuquel** [comment]
thank you so much for your quick and informative response,  i had 6. 7 and 8, uninstalling 6 fixed everything!!

many thanks!
